# -*- coding: utf-8 -*-

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mef-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mef
        tier: db
    spec:
      containers:
      - name: mef-db
        image: postgres:9.6
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: mef
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: mef
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mef
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: mef-db-data
      volumes:
      - name: mef-db-data
        hostPath:
          path: /data/docker/mef/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: mef-db
  labels:
    app: mef
    tier: db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30064
      name: db
  selector:
    app: mef
    tier: db
