# -*- coding: utf-8 -*-

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mef-indexer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mef
        tier: indexer
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          env:
          - name: bootstrap.memory_lock
            value: "true"
          securityContext:
            privileged: true
      containers:
      - name: mef-indexer
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        ports:
        - containerPort: 9300
          name: api
        - containerPort: 9200
          name: cluster
        env:
          - name: cluster.name
            value: mef
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: mef-indexer-data
      volumes:
      - name: mef-indexer-data
        hostPath:
          path: /data/docker/mef/elasticsearch/data
---
apiVersion: v1
kind: Service
metadata:
  name: mef-indexer
  labels:
    app: mef
    tier: indexer
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30062
      name: api
    - port: 9300
      nodePort: 30063
      name: cluster
  selector:
    app: mef
    tier: indexer
